name: java-ci-security

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  id-token: write

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build & Unit Test
        run: mvn -B clean verify

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar
          
      - name: list
        run: ls -la

  security-scans:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Make mvnw executable 
        run: chmod +x mvnw

      - name: Install Snyk CLI
        uses: snyk/actions/setup@v1

      # -------------------------
      # SCA — Dependency Scan
      # -------------------------
      - name: Snyk SCA (Dependencies)
        run: |
          ./mvnw dependency:tree -DoutputType=dot --batch-mode
          snyk test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}

      # -------------------------
      # SAST — Code Scan
      # -------------------------
      - name: Snyk SAST (Code)
        run: snyk code test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}

  dast:
    runs-on: ubuntu-latest
    needs: security-scans

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Pull OWASP ZAP 
        run: docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: OWASP ZAP Baseline Scan 
        run: | 
           docker run --rm --user root -v $(pwd):/zap/wrk ghcr.io/zaproxy/zaproxy:stable \
           zap-baseline.py \
           -t ec2-34-234-83-89.compute-1.amazonaws.com \
           -r zap-report.html \
           -x zap-report.xml \
           -I

      - name: Upload ZAP Report 
        uses: actions/upload-artifact@v4 
        with: 
          name: zap-report 
          path: zap-report.html
  
