name: java-ci-security

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  id-token: write

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build & Unit Test
        run: mvn -B clean verify

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.jar
          
      - name: list
        run: ls -la

  security-scans:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Make mvnw executable 
        run: chmod +x mvnw

      - name: Install Snyk CLI
        uses: snyk/actions/setup@v1

      # -------------------------
      # SCA — Dependency Scan
      # -------------------------
      - name: Snyk SCA (Dependencies)
        run: |
          ./mvnw dependency:tree -DoutputType=dot --batch-mode
          snyk test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}

      # -------------------------
      # SAST — Code Scan
      # -------------------------
      - name: Snyk SAST (Code)
        run: snyk code test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}

  dast:
    runs-on: ubuntu-latest
    needs: security-scans

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Snyk CLI 
        uses: snyk/actions/setup@v1

      - name: Snyk DAST Scan 
        run: | 
            snyk dast scan \ 
            --target-url="https://staging.my-java-app.example.com" \ 
            --severity-threshold=high   
        env: 
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
